changelog:
  categories:
  - title: Breaking Changes
    labels:
    - breaking-change
  - title: Features
    labels:
    - feature
    - enhancement
  - title: Bug fixes
    labels:
    - bug
  - title: Docs
    labels:
    - docs
    - documentation
  - title: Refactor
    labels:
    - refactor
  - title: Config
    labels:
    - config
    - configuration
  - title: Other Changes
    labels:
       - "*"
