changelog:
  categories:
  - title: Stuff to test
    labels:
    - breaking-change
  - title: Features 
    labels:
    - feature
  - title: Bug fixes 
    labels:
    - bug
  - title: Other Changes
    labels:
       - "*"
