changelog:
  categories:
  - title: Breaking Changes
    labels:
    - breaking-change
  - title: Features
    labels:
    - feature
  - title: Bug fixes
    labels:
    - bug
  - title: Docs
    labels:
    - docs
  - title: Other Changes
    labels:
       - "*"
